set -g default-terminal "screen-256color"
set -g terminal-overrides ',xterm-256color:RGB'
set-option -sa terminal-overrides ",xterm*:Tc"

set -g prefix C-a
set -g base-index 1
set -g set-clipboard on
set -g renumber-windows on
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g status-position top
set -g status-justify left
set -g status-style 'bg=#1e1e2e' # transparent
set -g mouse on

unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugin/tpm'
set -g @plugin 'tmux-plugin/tpm-sensible'
set -g @plugin 'tmux-plugin/tmux-resurrect'
set -g @plugin 'tmux-plugin/tmux-continuum'
set -g @plugin 'tmux-plugin/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/default/cyan'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
